apiVersion: v1
kind: Service
metadata:
  name: dev-api-service
  namespace: pluto
spec:
  type: ClusterIP
  selector:
    app: dev-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
