server:
  port: 8080

spring:
  application:
    name: pluto-api
  profiles:
    active: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.prettygoodorg.pluto_api
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'NULL'

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, livenessState, readinessState
